# Generated by Django 4.1.5 on 2023-07-31 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highscore',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
