# Generated by Django 4.1.5 on 2023-07-31 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_highscore_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz2HighScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Quiz3HighScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='HighScore',
            new_name='Quiz1HighScore',
        ),
    ]
