# Generated by Django 4.1.5 on 2023-07-31 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_quiz2highscore_quiz3highscore_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quiz3HighScore',
            new_name='HighScore',
        ),
        migrations.DeleteModel(
            name='Quiz1HighScore',
        ),
        migrations.DeleteModel(
            name='Quiz2HighScore',
        ),
    ]
