# Generated by Django 4.1.5 on 2023-07-31 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_quiz2highscore_quiz3highscore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz2highscore',
            old_name='score',
            new_name='quiz2_score',
        ),
        migrations.RemoveField(
            model_name='quiz2highscore',
            name='name',
        ),
        migrations.AddField(
            model_name='quiz2highscore',
            name='quiz2_name',
            field=models.CharField(default='Default Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz3highscore',
            name='name',
            field=models.CharField(default='Default Name', max_length=30),
        ),
    ]
