# Generated by Django 4.1.5 on 2023-07-31 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_rename_score_quiz2highscore_quiz2_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz2highscore',
            name='quiz2_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quiz3highscore',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
