# Generated by Django 4.1.5 on 2023-07-31 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_alter_quiz2highscore_quiz2_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz3HighScore',
        ),
        migrations.RenameField(
            model_name='quiz2highscore',
            old_name='quiz2_score',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='quiz2highscore',
            name='quiz2_name',
        ),
        migrations.AddField(
            model_name='quiz2highscore',
            name='name',
            field=models.CharField(blank=True, default='Default Name', max_length=30, null=True),
        ),
    ]
