# Generated by Django 4.1.5 on 2023-07-31 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_delete_quiz3highscore_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz2highscore',
            name='name',
            field=models.CharField(default='Default Name', max_length=30),
        ),
    ]
