# Generated by Django 4.1.5 on 2023-08-01 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_alter_quiz2highscore_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz3HighScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Name', max_length=30)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
