# Generated by Django 4.1.5 on 2023-08-01 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0010_quiz3highscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz2highscore',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='quiz3highscore',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
